import os
import base64
import logging
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.auth.transport.requests import Request
from langchain_groq import ChatGroq
from fpdf import FPDF
import tempfile
from datetime import datetime

logger = logging.getLogger("FloodSense.Notifications")

# --- Automated Alert Configuration (Reads from .env) ---
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = os.getenv("SMTP_SENDER_EMAIL", "khushdeepsingh5973@gmail.com") 
SENDER_PASSWORD = os.getenv("SMTP_SENDER_PASSWORD", "") 

# ✅ FIXED: Only one scope (no mismatch)
SCOPES = ['https://www.googleapis.com/auth/gmail.send']

# Load credentials from token.json (generated by OAuth flow)
TOKEN_FILE = "token.json"


def get_gmail_service():
    if not os.path.exists(TOKEN_FILE):
        logger.error("token.json not found. User must visit /authorize first.")
        return None

    creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

    # ✅ FIX: Auto refresh token
    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
            with open(TOKEN_FILE, "w") as token:
                token.write(creds.to_json())
        except Exception as e:
            logger.error(f"Token refresh failed: {e}")
            return None

    return build("gmail", "v1", credentials=creds)


def generate_flood_report_llama(ward_data):
    """
    Uses Groq Llama to generate a professional, urgent flood report.
    """
    llm = ChatGroq(
        api_key=os.getenv("LLAMA_API_KEY"),
        model=os.getenv("LLAMA_MODEL", "llama3-70b-8192")
    )
    
    ward_name = ward_data.get('WardName', 'Unknown')
    prob = ward_data.get('flood_probability', 0) * 100
    rain = ward_data.get('rainfall_mm', 0)
    elev = ward_data.get('elevation_m', 0)
    drain = ward_data.get('drainage_density', 0)
    urban = ward_data.get('impermeable_ratio', 0) * 100

    prompt = f"""
    You are an Emergency Response System AI. 
    Generate a highly professional, urgent HTML email report for the area of {ward_name}.
    Current Stats:
    - Flood Probability: {prob:.1f}%
    - Rainfall: {rain}mm
    - Elevation: {elev:.1f}m
    - Urban Density: {urban:.1f}%
    - Drainage Index: {drain:.3f}

    Include:
    1. A clear 'CRITICAL' heading.
    2. A brief analysis of why this area is at risk (mention how elevation and drainage density contribute).
    3. A 3-step action plan for local authorities.
    4. Keep it concise, using standard HTML tags.
    """
    
    try:
        response = llm.invoke(prompt)
        return response.content
    except Exception as e:
        logger.error(f"Llama Generation failed: {e}")
        return f"<h1>URGENT ALERT: {ward_name}</h1><p>Risk: {prob:.1f}%</p>"

def create_flood_report_pdf(ward_data, html_report):
    """
    Generates a premium, multi-section PDF report with training factors.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- HEADER ---
    pdf.set_fill_color(16, 20, 26) # Deep Sea Base
    pdf.rect(0, 0, 210, 45, 'F')
    
    pdf.set_xy(15, 15)
    pdf.set_font("helvetica", "B", 26)
    pdf.set_text_color(71, 234, 237) # Cyan Accent
    pdf.cell(0, 10, "FLOODSENSE AI", ln=True)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(180, 180, 180)
    pdf.cell(0, 7, "Predictive Intelligence Report | Delhi Resilience Initiative", ln=True)

    # --- RISK BADGE ---
    prob = ward_data.get('flood_probability', 0)
    status_label = "CRITICAL" if prob > 0.75 else "ELEVATED" if prob > 0.5 else "STABLE"
    status_color = (255, 77, 77) if prob > 0.75 else (252, 186, 3) if prob > 0.5 else (71, 234, 237)
    
    pdf.set_xy(140, 15)
    pdf.set_fill_color(*status_color)
    pdf.rect(140, 12, 55, 22, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("helvetica", "B", 16)
    pdf.set_xy(140, 18)
    pdf.cell(55, 10, status_label, ln=True, align='C')

    # --- REPORT INTRO ---
    pdf.set_xy(15, 55)
    pdf.set_text_color(20, 30, 40)
    pdf.set_font("helvetica", "B", 24)
    pdf.cell(0, 10, ward_data.get('WardName', 'Unknown Ward').upper(), ln=True)
    pdf.set_draw_color(71, 234, 237)
    pdf.line(15, 68, 195, 68)
    pdf.ln(15)

    # --- SECTION 1: RISK METRICS ---
    pdf.set_font("helvetica", "B", 13)
    pdf.set_text_color(16, 20, 26)
    pdf.cell(0, 10, "SECTION 1: ENVIRONMENTAL RISK METRICS", ln=True)
    pdf.ln(2)

    def add_metric_row(label, val, perc):
        pdf.set_font("helvetica", "", 11)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(60, 8, label)
        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(40, 8, f"{val}", ln=True)
        # Progress Bar
        pdf.set_fill_color(235, 235, 235)
        pdf.rect(15, pdf.get_y(), 100, 2.5, 'F')
        pdf.set_fill_color(71, 234, 237)
        pdf.rect(15, pdf.get_y(), max(2, perc * 100), 2.5, 'F')
        pdf.ln(6)

    add_metric_row("Rainfall Intensity", f"{ward_data.get('rainfall_mm')} mm/hr", min(ward_data.get('rainfall_mm', 0)/200, 1))
    add_metric_row("Elevation", f"{ward_data.get('elevation_m', 0):.1f} m", 0.7)
    add_metric_row("Surface Impermeability", f"{(ward_data.get('impermeable_ratio', 0)*100):.1f} %", ward_data.get('impermeable_ratio', 0))
    add_metric_row("Drainage Capacity", f"{ward_data.get('drainage_density', 0):.3f}", 0.4)

    # --- SECTION 2: PREDICTIVE METHODOLOGY ---
    pdf.ln(12)
    pdf.set_font("helvetica", "B", 13)
    pdf.cell(0, 10, "SECTION 2: Key Factors Influencing Flood Probability", ln=True)
    pdf.ln(2)
    pdf.set_font("helvetica", "", 9.5)
    pdf.set_text_color(60, 60, 60)
    
    methodology = [
    ("Rainfall", "Higher rainfall increases surface runoff, raising the likelihood of flooding. Intense or prolonged rain can overwhelm drainage systems quickly."),

    ("Elevation", "Low-lying areas accumulate water more easily, making them flood-prone. Higher elevation regions typically have better natural drainage."),

    ("Drainage Density", "Higher drainage density helps water disperse faster, reducing flood risk. Poor or sparse drainage leads to water accumulation and flooding."),

    ("Impermeable Ratio", "More concrete surfaces prevent water absorption, increasing runoff. Urban areas with high impermeability are more flood-prone."),

    ("Distance to Water", "Areas closer to rivers or water bodies are at higher flood risk. Water overflow or rising levels directly impact nearby regions.")
]
    
    for title, desc in methodology:
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 6, f"> {title}:", ln=True)
        pdf.set_font("helvetica", "", 9.5)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 5, desc)
        pdf.ln(2)

    # --- SECTION 3: STRATEGIC ACTION PLAN ---
    pdf.ln(5)
    pdf.set_fill_color(248, 250, 252)
    pdf.rect(15, pdf.get_y(), 180, 45, 'F')
    pdf.set_xy(20, pdf.get_y() + 5)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(180, 83, 9)
    pdf.cell(0, 10, "SECTION 3: STRATEGIC ACTION PLAN", ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(30, 41, 59)
    
    actions = [
        "Infrastructure: Clear blockages in primary storm-drainage arteries.",
        "Logistics: Pre-position rapid-extraction pumps in low-elevation clusters.",
        "Response: Dispatch early warning alerts to high-occupancy residential zones."
    ]
    for action in actions:
        pdf.set_x(25)
        pdf.multi_cell(0, 6, f"- {action}")

    # --- FOOTER ---
    pdf.set_y(-25)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 10, f"Issued: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | FloodSense AI Security Hub", align='C')
    
    fd, path = tempfile.mkstemp(suffix=".pdf")
    try:
        pdf.output(path)
    finally:
        os.close(fd)
    return path



def send_alert_auto(recipient_email, ward_data):
    """
    Automated trigger for flood alerts using Gmail API and Llama-powered content.
    """
    service = get_gmail_service()
    if not service:
        return False

    try:
        # Get sender identity
        user_profile = service.users().getProfile(userId="me").execute()
        sender_email = user_profile["emailAddress"]

        # 1. Generate Llama Report
        html_report = generate_flood_report_llama(ward_data)
        
        # 2. Generate PDF Report
        pdf_path = create_flood_report_pdf(ward_data, html_report)
        
        # 3. Prepare Multi-part message
        message = MIMEMultipart()
        message["to"] = recipient_email
        message["from"] = sender_email
        message["subject"] = f"🚨 ALERT: Critical Flood Risk in {ward_data.get('WardName')}"
        
        # Body
        message.attach(MIMEText(html_report, "html"))
        
        # Attachment
        with open(pdf_path, "rb") as attachment:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename=Flood_Report_{ward_data.get('WardName')}.pdf",
            )
            message.attach(part)
        
        raw = base64.urlsafe_b64encode(message.as_bytes()).decode()
        sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()
        
        # Cleanup PDF
        if os.path.exists(pdf_path):
            os.remove(pdf_path)
            
        logger.info(f"Llama Auto-Alert with PDF sent via Gmail API: {sent['id']}")
        return True

    except Exception as e:
        logger.error(f"Auto-Alert failed: {e}")
        return False